# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        bd_provider:
            entity:
                class: AppBundle:Usuario
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: login
                check_path: login

            provider: bd_provider

            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/recuperar-senha/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(login|esqueci-a-senha|enviar-recuperacao), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios, roles: ROLE_SUPER_ADMIN }
        - { path: ^/tipos, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPERVISOR: ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPERVISOR