# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.token_generator:
        class: AppBundle\Service\TokenGenerator
        arguments: ["@app.usuario_repository"]
    app.email_recuperacao_senha:
        class: AppBundle\Service\EmailRecuperacaoSenha
        arguments: ["@mailer", "@templating"]
    app.redefinidor_senha:
        class: AppBundle\Service\RedefinidorDeSenha
        arguments: ["@security.password_encoder"]
    app.usuario_repository:
        class: AppBundle\Repository\UsuarioRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Usuario
    app.ticket_repository:
        class: AppBundle\Repository\TicketRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Ticket
    app.email_ticket_aberto:
        class: AppBundle\Service\AcoesTicket\EmailTicketAberto
        arguments: ["@mailer", "@router"]
    app.email_interacao_ticket:
        class: AppBundle\Service\AcoesTicket\EmailInteracaoTicket
        arguments: ["@mailer", "@router"]
    app.email_fechar_ticket:
        class: AppBundle\Service\AcoesTicket\EmailFecharTicket
        arguments: ["@mailer", "@router"]